- name: add rancher helm repo
  command:
    cmd: "helm repo add rancher-stable https://releases.rancher.com/server-charts/stable"
  changed_when: true

- name: update helm repo
  command:
    cmd: "helm repo update"
  changed_when: true

- name: wait for k3s API server VIP {{ apiserver_endpoint }} to be available
  wait_for:
    host: "{{ apiserver_endpoint }}"
    port: 6443
    delay: 10

- name: create the cattle-system namespace for rancher
  command:
    cmd: kubectl create namespace cattle-system
  changed_when: true

#deploy rancher
- name: deploy rancher with dns name {{ rancher_dns_name }}
  command:
    cmd: helm install rancher rancher-stable/rancher --namespace cattle-system --set hostname="{{ rancher_dns_name }}" --set replicas="{{ rancher_replicas }}"
  changed_when: true
